# Generated by Django 4.2.14 on 2024-08-01 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Movieapp', '0002_mywatchlist_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mywatchlist',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchdetails', to='Movieapp.mystreamplatform'),
        ),
    ]
