# Generated by Django 4.2.14 on 2024-08-16 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mywatchlist',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='mywatchlist',
            name='number_rating',
            field=models.IntegerField(default=0),
        ),
    ]
