# Generated by Django 4.2.14 on 2024-08-02 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Movieapp', '0002_myreview_delete_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myreview',
            name='watchlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewinfo', to='Movieapp.mywatchlist'),
        ),
    ]
